name:
  CI CD for python,C, C++ and Java
  #this is the name of the program
#name: Multi-Language CI/CD
#this is the action word here that will say when it is pushed on main
#this tells the computer sever to run this action regardless of what branch it is
on:
  #this makes action occur on push req.
  push:
    branches: [main]
  #this makes action occur on pull req.
  pull_request:
    branches: [main]
jobs:
  build-c:
    name: Testing C Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build install
        run: sudo apt-get install build-essential -y
      - name: install GCC
        run: gcc -o myprogram src/main.c
      - name: run program
        run: ./myprogram
  build-cpp:
    name: Testing C++ Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: use gcc to build cpp
        run: sudo apt-get install build-essential -y
      - name: compiling code
        run: g++ -o hello_world src/main.cpp
      - name: execute program
        run: ./hello_world
  build-rust:
    name: Test Rust Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build Rust project
        run: rustc src/main.rs -o main

      - name: Run Rust tests
        run: ./main
  build-python:
    name: Testing Python Code
    runs-on: ubuntu-latest
    steps:
      #this makes it so actions can get code from the repo used in all code
      - uses: actions/checkout@v4
      #this is the python version setup
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: run python code
        run: python3 src/main.py
